export const HELIX_FOSSIL_ANSWERS = [
	'Yes',
	'No',
	'Maybe',
	'Ask again later',
	'Definitely',
	'Unlikely',
	'Absolutely',
	'Doubtful',
	'Signs point to yes',
	'Signs point to no',
	'The fossil is unclear',
	'Try again',
	'Fossil says no',
	'Fossil says yes',
	'Consult me later',
	'Outlook good',
	'Outlook not so good',
	'Cannot predict now',
	'Very likely',
	'Very unlikely',
] as const;
